### ISSUE TITLE
Does not build with current nugets and latest .Net targets

### ISSUE THREAD

**Issue by mach37** [Microsoft/SmartHotel360-Mobile#73]
Hello, it still does not build, please dont close, please help resovle this.

**Comment by pulimento** [comment]
Duplicate of #66

**Comment by pulimento** [comment]
Hi @mach37, I've just cloned the master branch of this repo, and it can run flawlessly, on Windows, on Visual Studio 2019. Please, in order to help you, I need more info about your software context. You do mention some NuGet package inconsistences, please can you share with me the exact error you are facing? You don't need to update any NuGet packages in order to make the project work. 

Please, can you clone a fresh copy and start again? Have you installed the latest version of Visual Studio? Which platform are yo using? Windows? Thanks

**Comment by mach37** [comment]
Please try it in a _different/new machine with a fresh download and build_. If I update the nugets, it says the other packages are out of sync and cannot build, due to comparability.

And I cannot update all, because the packages are interdependent but not compatible with the latest current version.

So far at work/school we did it in 3 machines and have the same issues.

**Comment by pulimento** [comment]
Hi again,

Just tried it with a brand new machine, with a fresh installation of Visual Studio 2019. Cloned directly from Visual Studio.

[Here is a video when I follow the proccess](https://streamable.com/rzzhr)

You are having problems updating the NuGet packages. Why you need to update it? Current versions are fine. Sure, some of them have got minor updates available, but those aren't needed. Do you have a special need in updating a package? If so, please let me know and we'll try something else. If not, please try the code without update anything. Nonethless, we will try to update all the packages (albeit it's not needed) in the near term.

**Comment by mach37** [comment]
I learned something new from your video. But rolling back to non-latest seems to work.
